### ISSUE TITLE
Maybe some screenshots of the final project running ?

### ISSUE THREAD

**Issue by Sanix-Darker** [HeavenMercy/StoryTeller-Engine#1]

**Comment by rich1richard** [comment]
the project is still a WIP. I will put a screenshot or two in the README.md to show how it looks. Thanks for the feedback

**Comment by rich1richard** [comment]
okay, I added a bunch of screenshots in the 'screenshots' folder and show two of them in the README.md
Please, tell me what you think about it

**Comment by Sanix-Darker** [comment]
I meant by that, the final result, but since it's a wip, i will close this issue !
Thanks for the response !
